# Generated by Django 5.1.1 on 2024-11-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_convert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
