# Generated by Django 5.1.1 on 2024-11-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfdata/'),
        ),
    ]
