# Generated by Django 5.1.1 on 2024-11-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('don_vi_soan_thao', models.CharField(max_length=100)),
                ('so_ky_hieu', models.CharField(max_length=30)),
                ('nguoi_ky', models.CharField(max_length=100)),
                ('ngay_ban_hanh', models.DateField()),
            ],
        ),
    ]
